/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ShellIndexRouteImport } from './routes/_shell/index'
import { Route as ShellBugsRouteImport } from './routes/_shell/bugs'
import { Route as ApiAuthMeRouteImport } from './routes/api/auth/me'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthGithubRouteImport } from './routes/api/auth/github'
import { Route as ApiAuthCallbackRouteImport } from './routes/api/auth/callback'
import { Route as ShellVersionsVersionRouteImport } from './routes/_shell/versions/$version'
import { Route as ShellVVersionRouteImport } from './routes/_shell/v/$version'
import { Route as ShellVersionsVersionIndexRouteImport } from './routes/_shell/versions/$version/index'
import { Route as ShellWorkstreamsVVersionRouteImport } from './routes/_shell/workstreams/v/$version'
import { Route as ShellVersionsVersionWorkstreamsSlugRouteImport } from './routes/_shell/versions/$version/workstreams/$slug'
import { Route as ShellVersionsVersionMilestonesMilestoneIdRouteImport } from './routes/_shell/versions/$version/milestones/$milestoneId'
import { Route as ShellVersionsVersionFeatureSlugRouteImport } from './routes/_shell/versions/$version/feature/$slug'
import { Route as ShellVersionsVersionDomainSlugRouteImport } from './routes/_shell/versions/$version/domain/$slug'
import { Route as ShellVersionsVersionDeliverablesDeliverableIdRouteImport } from './routes/_shell/versions/$version/deliverables/$deliverableId'
import { Route as ShellVersionsVersionAreaSlugRouteImport } from './routes/_shell/versions/$version/area/$slug'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellBugsRoute = ShellBugsRouteImport.update({
  id: '/bugs',
  path: '/bugs',
  getParentRoute: () => ShellRoute,
} as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGithubRoute = ApiAuthGithubRouteImport.update({
  id: '/api/auth/github',
  path: '/api/auth/github',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthCallbackRoute = ApiAuthCallbackRouteImport.update({
  id: '/api/auth/callback',
  path: '/api/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellVersionsVersionRoute = ShellVersionsVersionRouteImport.update({
  id: '/versions/$version',
  path: '/versions/$version',
  getParentRoute: () => ShellRoute,
} as any)
const ShellVVersionRoute = ShellVVersionRouteImport.update({
  id: '/v/$version',
  path: '/v/$version',
  getParentRoute: () => ShellRoute,
} as any)
const ShellVersionsVersionIndexRoute =
  ShellVersionsVersionIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ShellVersionsVersionRoute,
  } as any)
const ShellWorkstreamsVVersionRoute =
  ShellWorkstreamsVVersionRouteImport.update({
    id: '/workstreams/v/$version',
    path: '/workstreams/v/$version',
    getParentRoute: () => ShellRoute,
  } as any)
const ShellVersionsVersionWorkstreamsSlugRoute =
  ShellVersionsVersionWorkstreamsSlugRouteImport.update({
    id: '/workstreams/$slug',
    path: '/workstreams/$slug',
    getParentRoute: () => ShellVersionsVersionRoute,
  } as any)
const ShellVersionsVersionMilestonesMilestoneIdRoute =
  ShellVersionsVersionMilestonesMilestoneIdRouteImport.update({
    id: '/milestones/$milestoneId',
    path: '/milestones/$milestoneId',
    getParentRoute: () => ShellVersionsVersionRoute,
  } as any)
const ShellVersionsVersionFeatureSlugRoute =
  ShellVersionsVersionFeatureSlugRouteImport.update({
    id: '/feature/$slug',
    path: '/feature/$slug',
    getParentRoute: () => ShellVersionsVersionRoute,
  } as any)
const ShellVersionsVersionDomainSlugRoute =
  ShellVersionsVersionDomainSlugRouteImport.update({
    id: '/domain/$slug',
    path: '/domain/$slug',
    getParentRoute: () => ShellVersionsVersionRoute,
  } as any)
const ShellVersionsVersionDeliverablesDeliverableIdRoute =
  ShellVersionsVersionDeliverablesDeliverableIdRouteImport.update({
    id: '/deliverables/$deliverableId',
    path: '/deliverables/$deliverableId',
    getParentRoute: () => ShellVersionsVersionRoute,
  } as any)
const ShellVersionsVersionAreaSlugRoute =
  ShellVersionsVersionAreaSlugRouteImport.update({
    id: '/area/$slug',
    path: '/area/$slug',
    getParentRoute: () => ShellVersionsVersionRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/login': typeof LoginRoute
  '/bugs': typeof ShellBugsRoute
  '/v/$version': typeof ShellVVersionRoute
  '/versions/$version': typeof ShellVersionsVersionRouteWithChildren
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/github': typeof ApiAuthGithubRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/workstreams/v/$version': typeof ShellWorkstreamsVVersionRoute
  '/versions/$version/': typeof ShellVersionsVersionIndexRoute
  '/versions/$version/area/$slug': typeof ShellVersionsVersionAreaSlugRoute
  '/versions/$version/deliverables/$deliverableId': typeof ShellVersionsVersionDeliverablesDeliverableIdRoute
  '/versions/$version/domain/$slug': typeof ShellVersionsVersionDomainSlugRoute
  '/versions/$version/feature/$slug': typeof ShellVersionsVersionFeatureSlugRoute
  '/versions/$version/milestones/$milestoneId': typeof ShellVersionsVersionMilestonesMilestoneIdRoute
  '/versions/$version/workstreams/$slug': typeof ShellVersionsVersionWorkstreamsSlugRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/bugs': typeof ShellBugsRoute
  '/': typeof ShellIndexRoute
  '/v/$version': typeof ShellVVersionRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/github': typeof ApiAuthGithubRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/workstreams/v/$version': typeof ShellWorkstreamsVVersionRoute
  '/versions/$version': typeof ShellVersionsVersionIndexRoute
  '/versions/$version/area/$slug': typeof ShellVersionsVersionAreaSlugRoute
  '/versions/$version/deliverables/$deliverableId': typeof ShellVersionsVersionDeliverablesDeliverableIdRoute
  '/versions/$version/domain/$slug': typeof ShellVersionsVersionDomainSlugRoute
  '/versions/$version/feature/$slug': typeof ShellVersionsVersionFeatureSlugRoute
  '/versions/$version/milestones/$milestoneId': typeof ShellVersionsVersionMilestonesMilestoneIdRoute
  '/versions/$version/workstreams/$slug': typeof ShellVersionsVersionWorkstreamsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/login': typeof LoginRoute
  '/_shell/bugs': typeof ShellBugsRoute
  '/_shell/': typeof ShellIndexRoute
  '/_shell/v/$version': typeof ShellVVersionRoute
  '/_shell/versions/$version': typeof ShellVersionsVersionRouteWithChildren
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/github': typeof ApiAuthGithubRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/_shell/workstreams/v/$version': typeof ShellWorkstreamsVVersionRoute
  '/_shell/versions/$version/': typeof ShellVersionsVersionIndexRoute
  '/_shell/versions/$version/area/$slug': typeof ShellVersionsVersionAreaSlugRoute
  '/_shell/versions/$version/deliverables/$deliverableId': typeof ShellVersionsVersionDeliverablesDeliverableIdRoute
  '/_shell/versions/$version/domain/$slug': typeof ShellVersionsVersionDomainSlugRoute
  '/_shell/versions/$version/feature/$slug': typeof ShellVersionsVersionFeatureSlugRoute
  '/_shell/versions/$version/milestones/$milestoneId': typeof ShellVersionsVersionMilestonesMilestoneIdRoute
  '/_shell/versions/$version/workstreams/$slug': typeof ShellVersionsVersionWorkstreamsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/bugs'
    | '/v/$version'
    | '/versions/$version'
    | '/api/auth/callback'
    | '/api/auth/github'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/workstreams/v/$version'
    | '/versions/$version/'
    | '/versions/$version/area/$slug'
    | '/versions/$version/deliverables/$deliverableId'
    | '/versions/$version/domain/$slug'
    | '/versions/$version/feature/$slug'
    | '/versions/$version/milestones/$milestoneId'
    | '/versions/$version/workstreams/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/bugs'
    | '/'
    | '/v/$version'
    | '/api/auth/callback'
    | '/api/auth/github'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/workstreams/v/$version'
    | '/versions/$version'
    | '/versions/$version/area/$slug'
    | '/versions/$version/deliverables/$deliverableId'
    | '/versions/$version/domain/$slug'
    | '/versions/$version/feature/$slug'
    | '/versions/$version/milestones/$milestoneId'
    | '/versions/$version/workstreams/$slug'
  id:
    | '__root__'
    | '/_shell'
    | '/login'
    | '/_shell/bugs'
    | '/_shell/'
    | '/_shell/v/$version'
    | '/_shell/versions/$version'
    | '/api/auth/callback'
    | '/api/auth/github'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/_shell/workstreams/v/$version'
    | '/_shell/versions/$version/'
    | '/_shell/versions/$version/area/$slug'
    | '/_shell/versions/$version/deliverables/$deliverableId'
    | '/_shell/versions/$version/domain/$slug'
    | '/_shell/versions/$version/feature/$slug'
    | '/_shell/versions/$version/milestones/$milestoneId'
    | '/_shell/versions/$version/workstreams/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthCallbackRoute: typeof ApiAuthCallbackRoute
  ApiAuthGithubRoute: typeof ApiAuthGithubRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthMeRoute: typeof ApiAuthMeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/bugs': {
      id: '/_shell/bugs'
      path: '/bugs'
      fullPath: '/bugs'
      preLoaderRoute: typeof ShellBugsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/github': {
      id: '/api/auth/github'
      path: '/api/auth/github'
      fullPath: '/api/auth/github'
      preLoaderRoute: typeof ApiAuthGithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/callback': {
      id: '/api/auth/callback'
      path: '/api/auth/callback'
      fullPath: '/api/auth/callback'
      preLoaderRoute: typeof ApiAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/versions/$version': {
      id: '/_shell/versions/$version'
      path: '/versions/$version'
      fullPath: '/versions/$version'
      preLoaderRoute: typeof ShellVersionsVersionRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/v/$version': {
      id: '/_shell/v/$version'
      path: '/v/$version'
      fullPath: '/v/$version'
      preLoaderRoute: typeof ShellVVersionRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/versions/$version/': {
      id: '/_shell/versions/$version/'
      path: '/'
      fullPath: '/versions/$version/'
      preLoaderRoute: typeof ShellVersionsVersionIndexRouteImport
      parentRoute: typeof ShellVersionsVersionRoute
    }
    '/_shell/workstreams/v/$version': {
      id: '/_shell/workstreams/v/$version'
      path: '/workstreams/v/$version'
      fullPath: '/workstreams/v/$version'
      preLoaderRoute: typeof ShellWorkstreamsVVersionRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/versions/$version/workstreams/$slug': {
      id: '/_shell/versions/$version/workstreams/$slug'
      path: '/workstreams/$slug'
      fullPath: '/versions/$version/workstreams/$slug'
      preLoaderRoute: typeof ShellVersionsVersionWorkstreamsSlugRouteImport
      parentRoute: typeof ShellVersionsVersionRoute
    }
    '/_shell/versions/$version/milestones/$milestoneId': {
      id: '/_shell/versions/$version/milestones/$milestoneId'
      path: '/milestones/$milestoneId'
      fullPath: '/versions/$version/milestones/$milestoneId'
      preLoaderRoute: typeof ShellVersionsVersionMilestonesMilestoneIdRouteImport
      parentRoute: typeof ShellVersionsVersionRoute
    }
    '/_shell/versions/$version/feature/$slug': {
      id: '/_shell/versions/$version/feature/$slug'
      path: '/feature/$slug'
      fullPath: '/versions/$version/feature/$slug'
      preLoaderRoute: typeof ShellVersionsVersionFeatureSlugRouteImport
      parentRoute: typeof ShellVersionsVersionRoute
    }
    '/_shell/versions/$version/domain/$slug': {
      id: '/_shell/versions/$version/domain/$slug'
      path: '/domain/$slug'
      fullPath: '/versions/$version/domain/$slug'
      preLoaderRoute: typeof ShellVersionsVersionDomainSlugRouteImport
      parentRoute: typeof ShellVersionsVersionRoute
    }
    '/_shell/versions/$version/deliverables/$deliverableId': {
      id: '/_shell/versions/$version/deliverables/$deliverableId'
      path: '/deliverables/$deliverableId'
      fullPath: '/versions/$version/deliverables/$deliverableId'
      preLoaderRoute: typeof ShellVersionsVersionDeliverablesDeliverableIdRouteImport
      parentRoute: typeof ShellVersionsVersionRoute
    }
    '/_shell/versions/$version/area/$slug': {
      id: '/_shell/versions/$version/area/$slug'
      path: '/area/$slug'
      fullPath: '/versions/$version/area/$slug'
      preLoaderRoute: typeof ShellVersionsVersionAreaSlugRouteImport
      parentRoute: typeof ShellVersionsVersionRoute
    }
  }
}

interface ShellVersionsVersionRouteChildren {
  ShellVersionsVersionIndexRoute: typeof ShellVersionsVersionIndexRoute
  ShellVersionsVersionAreaSlugRoute: typeof ShellVersionsVersionAreaSlugRoute
  ShellVersionsVersionDeliverablesDeliverableIdRoute: typeof ShellVersionsVersionDeliverablesDeliverableIdRoute
  ShellVersionsVersionDomainSlugRoute: typeof ShellVersionsVersionDomainSlugRoute
  ShellVersionsVersionFeatureSlugRoute: typeof ShellVersionsVersionFeatureSlugRoute
  ShellVersionsVersionMilestonesMilestoneIdRoute: typeof ShellVersionsVersionMilestonesMilestoneIdRoute
  ShellVersionsVersionWorkstreamsSlugRoute: typeof ShellVersionsVersionWorkstreamsSlugRoute
}

const ShellVersionsVersionRouteChildren: ShellVersionsVersionRouteChildren = {
  ShellVersionsVersionIndexRoute: ShellVersionsVersionIndexRoute,
  ShellVersionsVersionAreaSlugRoute: ShellVersionsVersionAreaSlugRoute,
  ShellVersionsVersionDeliverablesDeliverableIdRoute:
    ShellVersionsVersionDeliverablesDeliverableIdRoute,
  ShellVersionsVersionDomainSlugRoute: ShellVersionsVersionDomainSlugRoute,
  ShellVersionsVersionFeatureSlugRoute: ShellVersionsVersionFeatureSlugRoute,
  ShellVersionsVersionMilestonesMilestoneIdRoute:
    ShellVersionsVersionMilestonesMilestoneIdRoute,
  ShellVersionsVersionWorkstreamsSlugRoute:
    ShellVersionsVersionWorkstreamsSlugRoute,
}

const ShellVersionsVersionRouteWithChildren =
  ShellVersionsVersionRoute._addFileChildren(ShellVersionsVersionRouteChildren)

interface ShellRouteChildren {
  ShellBugsRoute: typeof ShellBugsRoute
  ShellIndexRoute: typeof ShellIndexRoute
  ShellVVersionRoute: typeof ShellVVersionRoute
  ShellVersionsVersionRoute: typeof ShellVersionsVersionRouteWithChildren
  ShellWorkstreamsVVersionRoute: typeof ShellWorkstreamsVVersionRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellBugsRoute: ShellBugsRoute,
  ShellIndexRoute: ShellIndexRoute,
  ShellVVersionRoute: ShellVVersionRoute,
  ShellVersionsVersionRoute: ShellVersionsVersionRouteWithChildren,
  ShellWorkstreamsVVersionRoute: ShellWorkstreamsVVersionRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthCallbackRoute: ApiAuthCallbackRoute,
  ApiAuthGithubRoute: ApiAuthGithubRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthMeRoute: ApiAuthMeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
