/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MetricsRouteImport } from './routes/metrics'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ShellIndexRouteImport } from './routes/_shell/index'
import { Route as ShellBugsRouteImport } from './routes/_shell/bugs'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ShellDocsIndexRouteImport } from './routes/_shell/docs/index'
import { Route as ShellVVersionRouteImport } from './routes/_shell/v/$version'
import { Route as ShellVersionsVersionRouteImport } from './routes/_shell/versions/$version'
import { Route as ApiAdminSetupRouteImport } from './routes/api/admin/setup'
import { Route as ApiAuthGithubRouteImport } from './routes/api/auth/github'
import { Route as ApiAuthHubFinishRouteImport } from './routes/api/auth/hub-finish'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthMeRouteImport } from './routes/api/auth/me'
import { Route as ApiAuthPairRouteImport } from './routes/api/auth/pair'
import { Route as ApiV1TasksRouteImport } from './routes/api/v1/tasks'
import { Route as ApiWebhooksGithubRouteImport } from './routes/api/webhooks/github'
import { Route as SettingsAuthPairRouteImport } from './routes/settings/auth/pair'
import { Route as ShellVersionsVersionIndexRouteImport } from './routes/_shell/versions/$version/index'
import { Route as ShellWorkstreamsVVersionRouteImport } from './routes/_shell/workstreams/v/$version'
import { Route as ApiAdminAuthPairRouteImport } from './routes/api/admin/auth/pair'
import { Route as ApiAdminSetupStatusRouteImport } from './routes/api/admin/setup/status'
import { Route as ApiV1DeliveryVersionRouteImport } from './routes/api/v1/delivery/$version'
import { Route as ApiV1DeliveryLatestRouteImport } from './routes/api/v1/delivery/latest'
import { Route as ApiV1LinksTargetRouteImport } from './routes/api/v1/links/$target'
import { Route as ShellVVersionTasksNewRouteImport } from './routes/_shell/v/$version/tasks/new'
import { Route as ShellVVersionWWorkstreamRouteImport } from './routes/_shell/v/$version/w/$workstream'
import { Route as ShellVersionsVersionAreaSlugRouteImport } from './routes/_shell/versions/$version/area/$slug'
import { Route as ShellVersionsVersionDeliverablesDeliverableIdRouteImport } from './routes/_shell/versions/$version/deliverables/$deliverableId'
import { Route as ShellVersionsVersionDomainSlugRouteImport } from './routes/_shell/versions/$version/domain/$slug'
import { Route as ShellVersionsVersionFeatureSlugRouteImport } from './routes/_shell/versions/$version/feature/$slug'
import { Route as ShellVersionsVersionMilestonesMilestoneIdRouteImport } from './routes/_shell/versions/$version/milestones/$milestoneId'
import { Route as ShellVersionsVersionWorkstreamsSlugRouteImport } from './routes/_shell/versions/$version/workstreams/$slug'
import { Route as ShellVVersionWWorkstreamTasksNewRouteImport } from './routes/_shell/v/$version/w/$workstream/tasks/new'

const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MetricsRoute = MetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellBugsRoute = ShellBugsRouteImport.update({
  id: '/bugs',
  path: '/bugs',
  getParentRoute: () => ShellRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellDocsIndexRoute = ShellDocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellVVersionRoute = ShellVVersionRouteImport.update({
  id: '/v/$version',
  path: '/v/$version',
  getParentRoute: () => ShellRoute,
} as any)
const ShellVersionsVersionRoute = ShellVersionsVersionRouteImport.update({
  id: '/versions/$version',
  path: '/versions/$version',
  getParentRoute: () => ShellRoute,
} as any)
const ApiAdminSetupRoute = ApiAdminSetupRouteImport.update({
  id: '/api/admin/setup',
  path: '/api/admin/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGithubRoute = ApiAuthGithubRouteImport.update({
  id: '/api/auth/github',
  path: '/api/auth/github',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthHubFinishRoute = ApiAuthHubFinishRouteImport.update({
  id: '/api/auth/hub-finish',
  path: '/api/auth/hub-finish',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthPairRoute = ApiAuthPairRouteImport.update({
  id: '/api/auth/pair',
  path: '/api/auth/pair',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1TasksRoute = ApiV1TasksRouteImport.update({
  id: '/api/v1/tasks',
  path: '/api/v1/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksGithubRoute = ApiWebhooksGithubRouteImport.update({
  id: '/api/webhooks/github',
  path: '/api/webhooks/github',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAuthPairRoute = SettingsAuthPairRouteImport.update({
  id: '/settings/auth/pair',
  path: '/settings/auth/pair',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellVersionsVersionIndexRoute =
  ShellVersionsVersionIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ShellVersionsVersionRoute,
  } as any)
const ShellWorkstreamsVVersionRoute =
  ShellWorkstreamsVVersionRouteImport.update({
    id: '/workstreams/v/$version',
    path: '/workstreams/v/$version',
    getParentRoute: () => ShellRoute,
  } as any)
const ApiAdminAuthPairRoute = ApiAdminAuthPairRouteImport.update({
  id: '/api/admin/auth/pair',
  path: '/api/admin/auth/pair',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSetupStatusRoute = ApiAdminSetupStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => ApiAdminSetupRoute,
} as any)
const ApiV1DeliveryVersionRoute = ApiV1DeliveryVersionRouteImport.update({
  id: '/api/v1/delivery/$version',
  path: '/api/v1/delivery/$version',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1DeliveryLatestRoute = ApiV1DeliveryLatestRouteImport.update({
  id: '/api/v1/delivery/latest',
  path: '/api/v1/delivery/latest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1LinksTargetRoute = ApiV1LinksTargetRouteImport.update({
  id: '/api/v1/links/$target',
  path: '/api/v1/links/$target',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellVVersionTasksNewRoute = ShellVVersionTasksNewRouteImport.update({
  id: '/tasks/new',
  path: '/tasks/new',
  getParentRoute: () => ShellVVersionRoute,
} as any)
const ShellVVersionWWorkstreamRoute =
  ShellVVersionWWorkstreamRouteImport.update({
    id: '/w/$workstream',
    path: '/w/$workstream',
    getParentRoute: () => ShellVVersionRoute,
  } as any)
const ShellVersionsVersionAreaSlugRoute =
  ShellVersionsVersionAreaSlugRouteImport.update({
    id: '/area/$slug',
    path: '/area/$slug',
    getParentRoute: () => ShellVersionsVersionRoute,
  } as any)
const ShellVersionsVersionDeliverablesDeliverableIdRoute =
  ShellVersionsVersionDeliverablesDeliverableIdRouteImport.update({
    id: '/deliverables/$deliverableId',
    path: '/deliverables/$deliverableId',
    getParentRoute: () => ShellVersionsVersionRoute,
  } as any)
const ShellVersionsVersionDomainSlugRoute =
  ShellVersionsVersionDomainSlugRouteImport.update({
    id: '/domain/$slug',
    path: '/domain/$slug',
    getParentRoute: () => ShellVersionsVersionRoute,
  } as any)
const ShellVersionsVersionFeatureSlugRoute =
  ShellVersionsVersionFeatureSlugRouteImport.update({
    id: '/feature/$slug',
    path: '/feature/$slug',
    getParentRoute: () => ShellVersionsVersionRoute,
  } as any)
const ShellVersionsVersionMilestonesMilestoneIdRoute =
  ShellVersionsVersionMilestonesMilestoneIdRouteImport.update({
    id: '/milestones/$milestoneId',
    path: '/milestones/$milestoneId',
    getParentRoute: () => ShellVersionsVersionRoute,
  } as any)
const ShellVersionsVersionWorkstreamsSlugRoute =
  ShellVersionsVersionWorkstreamsSlugRouteImport.update({
    id: '/workstreams/$slug',
    path: '/workstreams/$slug',
    getParentRoute: () => ShellVersionsVersionRoute,
  } as any)
const ShellVVersionWWorkstreamTasksNewRoute =
  ShellVVersionWWorkstreamTasksNewRouteImport.update({
    id: '/tasks/new',
    path: '/tasks/new',
    getParentRoute: () => ShellVVersionWWorkstreamRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/login': typeof LoginRoute
  '/metrics': typeof MetricsRoute
  '/onboarding': typeof OnboardingRoute
  '/bugs': typeof ShellBugsRoute
  '/api/health': typeof ApiHealthRoute
  '/v/$version': typeof ShellVVersionRouteWithChildren
  '/versions/$version': typeof ShellVersionsVersionRouteWithChildren
  '/api/admin/setup': typeof ApiAdminSetupRouteWithChildren
  '/api/auth/github': typeof ApiAuthGithubRoute
  '/api/auth/hub-finish': typeof ApiAuthHubFinishRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/pair': typeof ApiAuthPairRoute
  '/api/v1/tasks': typeof ApiV1TasksRoute
  '/api/webhooks/github': typeof ApiWebhooksGithubRoute
  '/settings/auth/pair': typeof SettingsAuthPairRoute
  '/docs/': typeof ShellDocsIndexRoute
  '/workstreams/v/$version': typeof ShellWorkstreamsVVersionRoute
  '/api/admin/auth/pair': typeof ApiAdminAuthPairRoute
  '/api/admin/setup/status': typeof ApiAdminSetupStatusRoute
  '/api/v1/delivery/$version': typeof ApiV1DeliveryVersionRoute
  '/api/v1/delivery/latest': typeof ApiV1DeliveryLatestRoute
  '/api/v1/links/$target': typeof ApiV1LinksTargetRoute
  '/versions/$version/': typeof ShellVersionsVersionIndexRoute
  '/v/$version/tasks/new': typeof ShellVVersionTasksNewRoute
  '/v/$version/w/$workstream': typeof ShellVVersionWWorkstreamRouteWithChildren
  '/versions/$version/area/$slug': typeof ShellVersionsVersionAreaSlugRoute
  '/versions/$version/deliverables/$deliverableId': typeof ShellVersionsVersionDeliverablesDeliverableIdRoute
  '/versions/$version/domain/$slug': typeof ShellVersionsVersionDomainSlugRoute
  '/versions/$version/feature/$slug': typeof ShellVersionsVersionFeatureSlugRoute
  '/versions/$version/milestones/$milestoneId': typeof ShellVersionsVersionMilestonesMilestoneIdRoute
  '/versions/$version/workstreams/$slug': typeof ShellVersionsVersionWorkstreamsSlugRoute
  '/v/$version/w/$workstream/tasks/new': typeof ShellVVersionWWorkstreamTasksNewRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/metrics': typeof MetricsRoute
  '/onboarding': typeof OnboardingRoute
  '/bugs': typeof ShellBugsRoute
  '/api/health': typeof ApiHealthRoute
  '/': typeof ShellIndexRoute
  '/v/$version': typeof ShellVVersionRouteWithChildren
  '/api/admin/setup': typeof ApiAdminSetupRouteWithChildren
  '/api/auth/github': typeof ApiAuthGithubRoute
  '/api/auth/hub-finish': typeof ApiAuthHubFinishRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/pair': typeof ApiAuthPairRoute
  '/api/v1/tasks': typeof ApiV1TasksRoute
  '/api/webhooks/github': typeof ApiWebhooksGithubRoute
  '/settings/auth/pair': typeof SettingsAuthPairRoute
  '/docs': typeof ShellDocsIndexRoute
  '/workstreams/v/$version': typeof ShellWorkstreamsVVersionRoute
  '/api/admin/auth/pair': typeof ApiAdminAuthPairRoute
  '/api/admin/setup/status': typeof ApiAdminSetupStatusRoute
  '/api/v1/delivery/$version': typeof ApiV1DeliveryVersionRoute
  '/api/v1/delivery/latest': typeof ApiV1DeliveryLatestRoute
  '/api/v1/links/$target': typeof ApiV1LinksTargetRoute
  '/versions/$version': typeof ShellVersionsVersionIndexRoute
  '/v/$version/tasks/new': typeof ShellVVersionTasksNewRoute
  '/v/$version/w/$workstream': typeof ShellVVersionWWorkstreamRouteWithChildren
  '/versions/$version/area/$slug': typeof ShellVersionsVersionAreaSlugRoute
  '/versions/$version/deliverables/$deliverableId': typeof ShellVersionsVersionDeliverablesDeliverableIdRoute
  '/versions/$version/domain/$slug': typeof ShellVersionsVersionDomainSlugRoute
  '/versions/$version/feature/$slug': typeof ShellVersionsVersionFeatureSlugRoute
  '/versions/$version/milestones/$milestoneId': typeof ShellVersionsVersionMilestonesMilestoneIdRoute
  '/versions/$version/workstreams/$slug': typeof ShellVersionsVersionWorkstreamsSlugRoute
  '/v/$version/w/$workstream/tasks/new': typeof ShellVVersionWWorkstreamTasksNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/login': typeof LoginRoute
  '/metrics': typeof MetricsRoute
  '/onboarding': typeof OnboardingRoute
  '/_shell/bugs': typeof ShellBugsRoute
  '/api/health': typeof ApiHealthRoute
  '/_shell/': typeof ShellIndexRoute
  '/_shell/v/$version': typeof ShellVVersionRouteWithChildren
  '/_shell/versions/$version': typeof ShellVersionsVersionRouteWithChildren
  '/api/admin/setup': typeof ApiAdminSetupRouteWithChildren
  '/api/auth/github': typeof ApiAuthGithubRoute
  '/api/auth/hub-finish': typeof ApiAuthHubFinishRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/pair': typeof ApiAuthPairRoute
  '/api/v1/tasks': typeof ApiV1TasksRoute
  '/api/webhooks/github': typeof ApiWebhooksGithubRoute
  '/settings/auth/pair': typeof SettingsAuthPairRoute
  '/_shell/docs/': typeof ShellDocsIndexRoute
  '/_shell/workstreams/v/$version': typeof ShellWorkstreamsVVersionRoute
  '/api/admin/auth/pair': typeof ApiAdminAuthPairRoute
  '/api/admin/setup/status': typeof ApiAdminSetupStatusRoute
  '/api/v1/delivery/$version': typeof ApiV1DeliveryVersionRoute
  '/api/v1/delivery/latest': typeof ApiV1DeliveryLatestRoute
  '/api/v1/links/$target': typeof ApiV1LinksTargetRoute
  '/_shell/versions/$version/': typeof ShellVersionsVersionIndexRoute
  '/_shell/v/$version/tasks/new': typeof ShellVVersionTasksNewRoute
  '/_shell/v/$version/w/$workstream': typeof ShellVVersionWWorkstreamRouteWithChildren
  '/_shell/versions/$version/area/$slug': typeof ShellVersionsVersionAreaSlugRoute
  '/_shell/versions/$version/deliverables/$deliverableId': typeof ShellVersionsVersionDeliverablesDeliverableIdRoute
  '/_shell/versions/$version/domain/$slug': typeof ShellVersionsVersionDomainSlugRoute
  '/_shell/versions/$version/feature/$slug': typeof ShellVersionsVersionFeatureSlugRoute
  '/_shell/versions/$version/milestones/$milestoneId': typeof ShellVersionsVersionMilestonesMilestoneIdRoute
  '/_shell/versions/$version/workstreams/$slug': typeof ShellVersionsVersionWorkstreamsSlugRoute
  '/_shell/v/$version/w/$workstream/tasks/new': typeof ShellVVersionWWorkstreamTasksNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/metrics'
    | '/onboarding'
    | '/bugs'
    | '/api/health'
    | '/v/$version'
    | '/versions/$version'
    | '/api/admin/setup'
    | '/api/auth/github'
    | '/api/auth/hub-finish'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/pair'
    | '/api/v1/tasks'
    | '/api/webhooks/github'
    | '/settings/auth/pair'
    | '/docs/'
    | '/workstreams/v/$version'
    | '/api/admin/auth/pair'
    | '/api/admin/setup/status'
    | '/api/v1/delivery/$version'
    | '/api/v1/delivery/latest'
    | '/api/v1/links/$target'
    | '/versions/$version/'
    | '/v/$version/tasks/new'
    | '/v/$version/w/$workstream'
    | '/versions/$version/area/$slug'
    | '/versions/$version/deliverables/$deliverableId'
    | '/versions/$version/domain/$slug'
    | '/versions/$version/feature/$slug'
    | '/versions/$version/milestones/$milestoneId'
    | '/versions/$version/workstreams/$slug'
    | '/v/$version/w/$workstream/tasks/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/metrics'
    | '/onboarding'
    | '/bugs'
    | '/api/health'
    | '/'
    | '/v/$version'
    | '/api/admin/setup'
    | '/api/auth/github'
    | '/api/auth/hub-finish'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/pair'
    | '/api/v1/tasks'
    | '/api/webhooks/github'
    | '/settings/auth/pair'
    | '/docs'
    | '/workstreams/v/$version'
    | '/api/admin/auth/pair'
    | '/api/admin/setup/status'
    | '/api/v1/delivery/$version'
    | '/api/v1/delivery/latest'
    | '/api/v1/links/$target'
    | '/versions/$version'
    | '/v/$version/tasks/new'
    | '/v/$version/w/$workstream'
    | '/versions/$version/area/$slug'
    | '/versions/$version/deliverables/$deliverableId'
    | '/versions/$version/domain/$slug'
    | '/versions/$version/feature/$slug'
    | '/versions/$version/milestones/$milestoneId'
    | '/versions/$version/workstreams/$slug'
    | '/v/$version/w/$workstream/tasks/new'
  id:
    | '__root__'
    | '/_shell'
    | '/login'
    | '/metrics'
    | '/onboarding'
    | '/_shell/bugs'
    | '/api/health'
    | '/_shell/'
    | '/_shell/v/$version'
    | '/_shell/versions/$version'
    | '/api/admin/setup'
    | '/api/auth/github'
    | '/api/auth/hub-finish'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/pair'
    | '/api/v1/tasks'
    | '/api/webhooks/github'
    | '/settings/auth/pair'
    | '/_shell/docs/'
    | '/_shell/workstreams/v/$version'
    | '/api/admin/auth/pair'
    | '/api/admin/setup/status'
    | '/api/v1/delivery/$version'
    | '/api/v1/delivery/latest'
    | '/api/v1/links/$target'
    | '/_shell/versions/$version/'
    | '/_shell/v/$version/tasks/new'
    | '/_shell/v/$version/w/$workstream'
    | '/_shell/versions/$version/area/$slug'
    | '/_shell/versions/$version/deliverables/$deliverableId'
    | '/_shell/versions/$version/domain/$slug'
    | '/_shell/versions/$version/feature/$slug'
    | '/_shell/versions/$version/milestones/$milestoneId'
    | '/_shell/versions/$version/workstreams/$slug'
    | '/_shell/v/$version/w/$workstream/tasks/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
  LoginRoute: typeof LoginRoute
  MetricsRoute: typeof MetricsRoute
  OnboardingRoute: typeof OnboardingRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiAdminSetupRoute: typeof ApiAdminSetupRouteWithChildren
  ApiAuthGithubRoute: typeof ApiAuthGithubRoute
  ApiAuthHubFinishRoute: typeof ApiAuthHubFinishRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthMeRoute: typeof ApiAuthMeRoute
  ApiAuthPairRoute: typeof ApiAuthPairRoute
  ApiV1TasksRoute: typeof ApiV1TasksRoute
  ApiWebhooksGithubRoute: typeof ApiWebhooksGithubRoute
  SettingsAuthPairRoute: typeof SettingsAuthPairRoute
  ApiAdminAuthPairRoute: typeof ApiAdminAuthPairRoute
  ApiV1DeliveryVersionRoute: typeof ApiV1DeliveryVersionRoute
  ApiV1DeliveryLatestRoute: typeof ApiV1DeliveryLatestRoute
  ApiV1LinksTargetRoute: typeof ApiV1LinksTargetRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metrics': {
      id: '/metrics'
      path: '/metrics'
      fullPath: '/metrics'
      preLoaderRoute: typeof MetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/bugs': {
      id: '/_shell/bugs'
      path: '/bugs'
      fullPath: '/bugs'
      preLoaderRoute: typeof ShellBugsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/docs/': {
      id: '/_shell/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof ShellDocsIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/v/$version': {
      id: '/_shell/v/$version'
      path: '/v/$version'
      fullPath: '/v/$version'
      preLoaderRoute: typeof ShellVVersionRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/versions/$version': {
      id: '/_shell/versions/$version'
      path: '/versions/$version'
      fullPath: '/versions/$version'
      preLoaderRoute: typeof ShellVersionsVersionRouteImport
      parentRoute: typeof ShellRoute
    }
    '/api/admin/setup': {
      id: '/api/admin/setup'
      path: '/api/admin/setup'
      fullPath: '/api/admin/setup'
      preLoaderRoute: typeof ApiAdminSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/github': {
      id: '/api/auth/github'
      path: '/api/auth/github'
      fullPath: '/api/auth/github'
      preLoaderRoute: typeof ApiAuthGithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/hub-finish': {
      id: '/api/auth/hub-finish'
      path: '/api/auth/hub-finish'
      fullPath: '/api/auth/hub-finish'
      preLoaderRoute: typeof ApiAuthHubFinishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/pair': {
      id: '/api/auth/pair'
      path: '/api/auth/pair'
      fullPath: '/api/auth/pair'
      preLoaderRoute: typeof ApiAuthPairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/tasks': {
      id: '/api/v1/tasks'
      path: '/api/v1/tasks'
      fullPath: '/api/v1/tasks'
      preLoaderRoute: typeof ApiV1TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/github': {
      id: '/api/webhooks/github'
      path: '/api/webhooks/github'
      fullPath: '/api/webhooks/github'
      preLoaderRoute: typeof ApiWebhooksGithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/auth/pair': {
      id: '/settings/auth/pair'
      path: '/settings/auth/pair'
      fullPath: '/settings/auth/pair'
      preLoaderRoute: typeof SettingsAuthPairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/versions/$version/': {
      id: '/_shell/versions/$version/'
      path: '/'
      fullPath: '/versions/$version/'
      preLoaderRoute: typeof ShellVersionsVersionIndexRouteImport
      parentRoute: typeof ShellVersionsVersionRoute
    }
    '/_shell/workstreams/v/$version': {
      id: '/_shell/workstreams/v/$version'
      path: '/workstreams/v/$version'
      fullPath: '/workstreams/v/$version'
      preLoaderRoute: typeof ShellWorkstreamsVVersionRouteImport
      parentRoute: typeof ShellRoute
    }
    '/api/admin/auth/pair': {
      id: '/api/admin/auth/pair'
      path: '/api/admin/auth/pair'
      fullPath: '/api/admin/auth/pair'
      preLoaderRoute: typeof ApiAdminAuthPairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/setup/status': {
      id: '/api/admin/setup/status'
      path: '/status'
      fullPath: '/api/admin/setup/status'
      preLoaderRoute: typeof ApiAdminSetupStatusRouteImport
      parentRoute: typeof ApiAdminSetupRoute
    }
    '/api/v1/delivery/$version': {
      id: '/api/v1/delivery/$version'
      path: '/api/v1/delivery/$version'
      fullPath: '/api/v1/delivery/$version'
      preLoaderRoute: typeof ApiV1DeliveryVersionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/delivery/latest': {
      id: '/api/v1/delivery/latest'
      path: '/api/v1/delivery/latest'
      fullPath: '/api/v1/delivery/latest'
      preLoaderRoute: typeof ApiV1DeliveryLatestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/links/$target': {
      id: '/api/v1/links/$target'
      path: '/api/v1/links/$target'
      fullPath: '/api/v1/links/$target'
      preLoaderRoute: typeof ApiV1LinksTargetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/v/$version/tasks/new': {
      id: '/_shell/v/$version/tasks/new'
      path: '/tasks/new'
      fullPath: '/v/$version/tasks/new'
      preLoaderRoute: typeof ShellVVersionTasksNewRouteImport
      parentRoute: typeof ShellVVersionRoute
    }
    '/_shell/v/$version/w/$workstream': {
      id: '/_shell/v/$version/w/$workstream'
      path: '/w/$workstream'
      fullPath: '/v/$version/w/$workstream'
      preLoaderRoute: typeof ShellVVersionWWorkstreamRouteImport
      parentRoute: typeof ShellVVersionRoute
    }
    '/_shell/versions/$version/area/$slug': {
      id: '/_shell/versions/$version/area/$slug'
      path: '/area/$slug'
      fullPath: '/versions/$version/area/$slug'
      preLoaderRoute: typeof ShellVersionsVersionAreaSlugRouteImport
      parentRoute: typeof ShellVersionsVersionRoute
    }
    '/_shell/versions/$version/deliverables/$deliverableId': {
      id: '/_shell/versions/$version/deliverables/$deliverableId'
      path: '/deliverables/$deliverableId'
      fullPath: '/versions/$version/deliverables/$deliverableId'
      preLoaderRoute: typeof ShellVersionsVersionDeliverablesDeliverableIdRouteImport
      parentRoute: typeof ShellVersionsVersionRoute
    }
    '/_shell/versions/$version/domain/$slug': {
      id: '/_shell/versions/$version/domain/$slug'
      path: '/domain/$slug'
      fullPath: '/versions/$version/domain/$slug'
      preLoaderRoute: typeof ShellVersionsVersionDomainSlugRouteImport
      parentRoute: typeof ShellVersionsVersionRoute
    }
    '/_shell/versions/$version/feature/$slug': {
      id: '/_shell/versions/$version/feature/$slug'
      path: '/feature/$slug'
      fullPath: '/versions/$version/feature/$slug'
      preLoaderRoute: typeof ShellVersionsVersionFeatureSlugRouteImport
      parentRoute: typeof ShellVersionsVersionRoute
    }
    '/_shell/versions/$version/milestones/$milestoneId': {
      id: '/_shell/versions/$version/milestones/$milestoneId'
      path: '/milestones/$milestoneId'
      fullPath: '/versions/$version/milestones/$milestoneId'
      preLoaderRoute: typeof ShellVersionsVersionMilestonesMilestoneIdRouteImport
      parentRoute: typeof ShellVersionsVersionRoute
    }
    '/_shell/versions/$version/workstreams/$slug': {
      id: '/_shell/versions/$version/workstreams/$slug'
      path: '/workstreams/$slug'
      fullPath: '/versions/$version/workstreams/$slug'
      preLoaderRoute: typeof ShellVersionsVersionWorkstreamsSlugRouteImport
      parentRoute: typeof ShellVersionsVersionRoute
    }
    '/_shell/v/$version/w/$workstream/tasks/new': {
      id: '/_shell/v/$version/w/$workstream/tasks/new'
      path: '/tasks/new'
      fullPath: '/v/$version/w/$workstream/tasks/new'
      preLoaderRoute: typeof ShellVVersionWWorkstreamTasksNewRouteImport
      parentRoute: typeof ShellVVersionWWorkstreamRoute
    }
  }
}

interface ShellVVersionWWorkstreamRouteChildren {
  ShellVVersionWWorkstreamTasksNewRoute: typeof ShellVVersionWWorkstreamTasksNewRoute
}

const ShellVVersionWWorkstreamRouteChildren: ShellVVersionWWorkstreamRouteChildren =
  {
    ShellVVersionWWorkstreamTasksNewRoute:
      ShellVVersionWWorkstreamTasksNewRoute,
  }

const ShellVVersionWWorkstreamRouteWithChildren =
  ShellVVersionWWorkstreamRoute._addFileChildren(
    ShellVVersionWWorkstreamRouteChildren,
  )

interface ShellVVersionRouteChildren {
  ShellVVersionTasksNewRoute: typeof ShellVVersionTasksNewRoute
  ShellVVersionWWorkstreamRoute: typeof ShellVVersionWWorkstreamRouteWithChildren
}

const ShellVVersionRouteChildren: ShellVVersionRouteChildren = {
  ShellVVersionTasksNewRoute: ShellVVersionTasksNewRoute,
  ShellVVersionWWorkstreamRoute: ShellVVersionWWorkstreamRouteWithChildren,
}

const ShellVVersionRouteWithChildren = ShellVVersionRoute._addFileChildren(
  ShellVVersionRouteChildren,
)

interface ShellVersionsVersionRouteChildren {
  ShellVersionsVersionIndexRoute: typeof ShellVersionsVersionIndexRoute
  ShellVersionsVersionAreaSlugRoute: typeof ShellVersionsVersionAreaSlugRoute
  ShellVersionsVersionDeliverablesDeliverableIdRoute: typeof ShellVersionsVersionDeliverablesDeliverableIdRoute
  ShellVersionsVersionDomainSlugRoute: typeof ShellVersionsVersionDomainSlugRoute
  ShellVersionsVersionFeatureSlugRoute: typeof ShellVersionsVersionFeatureSlugRoute
  ShellVersionsVersionMilestonesMilestoneIdRoute: typeof ShellVersionsVersionMilestonesMilestoneIdRoute
  ShellVersionsVersionWorkstreamsSlugRoute: typeof ShellVersionsVersionWorkstreamsSlugRoute
}

const ShellVersionsVersionRouteChildren: ShellVersionsVersionRouteChildren = {
  ShellVersionsVersionIndexRoute: ShellVersionsVersionIndexRoute,
  ShellVersionsVersionAreaSlugRoute: ShellVersionsVersionAreaSlugRoute,
  ShellVersionsVersionDeliverablesDeliverableIdRoute:
    ShellVersionsVersionDeliverablesDeliverableIdRoute,
  ShellVersionsVersionDomainSlugRoute: ShellVersionsVersionDomainSlugRoute,
  ShellVersionsVersionFeatureSlugRoute: ShellVersionsVersionFeatureSlugRoute,
  ShellVersionsVersionMilestonesMilestoneIdRoute:
    ShellVersionsVersionMilestonesMilestoneIdRoute,
  ShellVersionsVersionWorkstreamsSlugRoute:
    ShellVersionsVersionWorkstreamsSlugRoute,
}

const ShellVersionsVersionRouteWithChildren =
  ShellVersionsVersionRoute._addFileChildren(ShellVersionsVersionRouteChildren)

interface ShellRouteChildren {
  ShellBugsRoute: typeof ShellBugsRoute
  ShellIndexRoute: typeof ShellIndexRoute
  ShellVVersionRoute: typeof ShellVVersionRouteWithChildren
  ShellVersionsVersionRoute: typeof ShellVersionsVersionRouteWithChildren
  ShellDocsIndexRoute: typeof ShellDocsIndexRoute
  ShellWorkstreamsVVersionRoute: typeof ShellWorkstreamsVVersionRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellBugsRoute: ShellBugsRoute,
  ShellIndexRoute: ShellIndexRoute,
  ShellVVersionRoute: ShellVVersionRouteWithChildren,
  ShellVersionsVersionRoute: ShellVersionsVersionRouteWithChildren,
  ShellDocsIndexRoute: ShellDocsIndexRoute,
  ShellWorkstreamsVVersionRoute: ShellWorkstreamsVVersionRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

interface ApiAdminSetupRouteChildren {
  ApiAdminSetupStatusRoute: typeof ApiAdminSetupStatusRoute
}

const ApiAdminSetupRouteChildren: ApiAdminSetupRouteChildren = {
  ApiAdminSetupStatusRoute: ApiAdminSetupStatusRoute,
}

const ApiAdminSetupRouteWithChildren = ApiAdminSetupRoute._addFileChildren(
  ApiAdminSetupRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
  LoginRoute: LoginRoute,
  MetricsRoute: MetricsRoute,
  OnboardingRoute: OnboardingRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiAdminSetupRoute: ApiAdminSetupRouteWithChildren,
  ApiAuthGithubRoute: ApiAuthGithubRoute,
  ApiAuthHubFinishRoute: ApiAuthHubFinishRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthMeRoute: ApiAuthMeRoute,
  ApiAuthPairRoute: ApiAuthPairRoute,
  ApiV1TasksRoute: ApiV1TasksRoute,
  ApiWebhooksGithubRoute: ApiWebhooksGithubRoute,
  SettingsAuthPairRoute: SettingsAuthPairRoute,
  ApiAdminAuthPairRoute: ApiAdminAuthPairRoute,
  ApiV1DeliveryVersionRoute: ApiV1DeliveryVersionRoute,
  ApiV1DeliveryLatestRoute: ApiV1DeliveryLatestRoute,
  ApiV1LinksTargetRoute: ApiV1LinksTargetRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
