/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MetricsRouteImport } from './routes/metrics'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ShellIndexRouteImport } from './routes/_shell/index'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ShellBugsRouteImport } from './routes/_shell/bugs'
import { Route as ShellDocsIndexRouteImport } from './routes/_shell/docs/index'
import { Route as SettingsAuthPairRouteImport } from './routes/settings/auth/pair'
import { Route as ApiWebhooksGithubRouteImport } from './routes/api/webhooks/github'
import { Route as ApiAuthMeRouteImport } from './routes/api/auth/me'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthHubFinishRouteImport } from './routes/api/auth/hub-finish'
import { Route as ApiAuthGithubRouteImport } from './routes/api/auth/github'
import { Route as ShellVersionsVersionRouteImport } from './routes/_shell/versions/$version'
import { Route as ShellVVersionRouteImport } from './routes/_shell/v/$version'
import { Route as ShellVersionsVersionIndexRouteImport } from './routes/_shell/versions/$version/index'
import { Route as ShellDocsProposalsIndexRouteImport } from './routes/_shell/docs/proposals/index'
import { Route as ShellDocsCatalogIndexRouteImport } from './routes/_shell/docs/catalog/index'
import { Route as ShellWorkstreamsVVersionRouteImport } from './routes/_shell/workstreams/v/$version'
import { Route as ShellDocsProposalsNewRouteImport } from './routes/_shell/docs/proposals/new'
import { Route as ShellDocsCatalogSlugRouteImport } from './routes/_shell/docs/catalog/$slug'
import { Route as ShellDocsProposalsIdIndexRouteImport } from './routes/_shell/docs/proposals/$id/index'
import { Route as ShellVersionsVersionWorkstreamsSlugRouteImport } from './routes/_shell/versions/$version/workstreams/$slug'
import { Route as ShellVersionsVersionMilestonesMilestoneIdRouteImport } from './routes/_shell/versions/$version/milestones/$milestoneId'
import { Route as ShellVersionsVersionFeatureSlugRouteImport } from './routes/_shell/versions/$version/feature/$slug'
import { Route as ShellVersionsVersionDomainSlugRouteImport } from './routes/_shell/versions/$version/domain/$slug'
import { Route as ShellVersionsVersionDeliverablesDeliverableIdRouteImport } from './routes/_shell/versions/$version/deliverables/$deliverableId'
import { Route as ShellVersionsVersionAreaSlugRouteImport } from './routes/_shell/versions/$version/area/$slug'
import { Route as ShellVVersionWWorkstreamRouteImport } from './routes/_shell/v/$version/w/$workstream'
import { Route as ShellVVersionTasksNewRouteImport } from './routes/_shell/v/$version/tasks/new'
import { Route as ShellDocsProposalsIdChangesNewRouteImport } from './routes/_shell/docs/proposals/$id/changes/new'
import { Route as ShellDocsProposalsIdChangesChangeIdRouteImport } from './routes/_shell/docs/proposals/$id/changes/$changeId'
import { Route as ShellVVersionWWorkstreamTasksNewRouteImport } from './routes/_shell/v/$version/w/$workstream/tasks/new'

const MetricsRoute = MetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellBugsRoute = ShellBugsRouteImport.update({
  id: '/bugs',
  path: '/bugs',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDocsIndexRoute = ShellDocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => ShellRoute,
} as any)
const SettingsAuthPairRoute = SettingsAuthPairRouteImport.update({
  id: '/settings/auth/pair',
  path: '/settings/auth/pair',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksGithubRoute = ApiWebhooksGithubRouteImport.update({
  id: '/api/webhooks/github',
  path: '/api/webhooks/github',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthHubFinishRoute = ApiAuthHubFinishRouteImport.update({
  id: '/api/auth/hub-finish',
  path: '/api/auth/hub-finish',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGithubRoute = ApiAuthGithubRouteImport.update({
  id: '/api/auth/github',
  path: '/api/auth/github',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellVersionsVersionRoute = ShellVersionsVersionRouteImport.update({
  id: '/versions/$version',
  path: '/versions/$version',
  getParentRoute: () => ShellRoute,
} as any)
const ShellVVersionRoute = ShellVVersionRouteImport.update({
  id: '/v/$version',
  path: '/v/$version',
  getParentRoute: () => ShellRoute,
} as any)
const ShellVersionsVersionIndexRoute =
  ShellVersionsVersionIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ShellVersionsVersionRoute,
  } as any)
const ShellDocsProposalsIndexRoute = ShellDocsProposalsIndexRouteImport.update({
  id: '/docs/proposals/',
  path: '/docs/proposals/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDocsCatalogIndexRoute = ShellDocsCatalogIndexRouteImport.update({
  id: '/docs/catalog/',
  path: '/docs/catalog/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellWorkstreamsVVersionRoute =
  ShellWorkstreamsVVersionRouteImport.update({
    id: '/workstreams/v/$version',
    path: '/workstreams/v/$version',
    getParentRoute: () => ShellRoute,
  } as any)
const ShellDocsProposalsNewRoute = ShellDocsProposalsNewRouteImport.update({
  id: '/docs/proposals/new',
  path: '/docs/proposals/new',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDocsCatalogSlugRoute = ShellDocsCatalogSlugRouteImport.update({
  id: '/docs/catalog/$slug',
  path: '/docs/catalog/$slug',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDocsProposalsIdIndexRoute =
  ShellDocsProposalsIdIndexRouteImport.update({
    id: '/docs/proposals/$id/',
    path: '/docs/proposals/$id/',
    getParentRoute: () => ShellRoute,
  } as any)
const ShellVersionsVersionWorkstreamsSlugRoute =
  ShellVersionsVersionWorkstreamsSlugRouteImport.update({
    id: '/workstreams/$slug',
    path: '/workstreams/$slug',
    getParentRoute: () => ShellVersionsVersionRoute,
  } as any)
const ShellVersionsVersionMilestonesMilestoneIdRoute =
  ShellVersionsVersionMilestonesMilestoneIdRouteImport.update({
    id: '/milestones/$milestoneId',
    path: '/milestones/$milestoneId',
    getParentRoute: () => ShellVersionsVersionRoute,
  } as any)
const ShellVersionsVersionFeatureSlugRoute =
  ShellVersionsVersionFeatureSlugRouteImport.update({
    id: '/feature/$slug',
    path: '/feature/$slug',
    getParentRoute: () => ShellVersionsVersionRoute,
  } as any)
const ShellVersionsVersionDomainSlugRoute =
  ShellVersionsVersionDomainSlugRouteImport.update({
    id: '/domain/$slug',
    path: '/domain/$slug',
    getParentRoute: () => ShellVersionsVersionRoute,
  } as any)
const ShellVersionsVersionDeliverablesDeliverableIdRoute =
  ShellVersionsVersionDeliverablesDeliverableIdRouteImport.update({
    id: '/deliverables/$deliverableId',
    path: '/deliverables/$deliverableId',
    getParentRoute: () => ShellVersionsVersionRoute,
  } as any)
const ShellVersionsVersionAreaSlugRoute =
  ShellVersionsVersionAreaSlugRouteImport.update({
    id: '/area/$slug',
    path: '/area/$slug',
    getParentRoute: () => ShellVersionsVersionRoute,
  } as any)
const ShellVVersionWWorkstreamRoute =
  ShellVVersionWWorkstreamRouteImport.update({
    id: '/w/$workstream',
    path: '/w/$workstream',
    getParentRoute: () => ShellVVersionRoute,
  } as any)
const ShellVVersionTasksNewRoute = ShellVVersionTasksNewRouteImport.update({
  id: '/tasks/new',
  path: '/tasks/new',
  getParentRoute: () => ShellVVersionRoute,
} as any)
const ShellDocsProposalsIdChangesNewRoute =
  ShellDocsProposalsIdChangesNewRouteImport.update({
    id: '/docs/proposals/$id/changes/new',
    path: '/docs/proposals/$id/changes/new',
    getParentRoute: () => ShellRoute,
  } as any)
const ShellDocsProposalsIdChangesChangeIdRoute =
  ShellDocsProposalsIdChangesChangeIdRouteImport.update({
    id: '/docs/proposals/$id/changes/$changeId',
    path: '/docs/proposals/$id/changes/$changeId',
    getParentRoute: () => ShellRoute,
  } as any)
const ShellVVersionWWorkstreamTasksNewRoute =
  ShellVVersionWWorkstreamTasksNewRouteImport.update({
    id: '/tasks/new',
    path: '/tasks/new',
    getParentRoute: () => ShellVVersionWWorkstreamRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/login': typeof LoginRoute
  '/metrics': typeof MetricsRoute
  '/bugs': typeof ShellBugsRoute
  '/api/health': typeof ApiHealthRoute
  '/v/$version': typeof ShellVVersionRouteWithChildren
  '/versions/$version': typeof ShellVersionsVersionRouteWithChildren
  '/api/auth/github': typeof ApiAuthGithubRoute
  '/api/auth/hub-finish': typeof ApiAuthHubFinishRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/webhooks/github': typeof ApiWebhooksGithubRoute
  '/settings/auth/pair': typeof SettingsAuthPairRoute
  '/docs/': typeof ShellDocsIndexRoute
  '/docs/catalog/$slug': typeof ShellDocsCatalogSlugRoute
  '/docs/proposals/new': typeof ShellDocsProposalsNewRoute
  '/workstreams/v/$version': typeof ShellWorkstreamsVVersionRoute
  '/docs/catalog/': typeof ShellDocsCatalogIndexRoute
  '/docs/proposals/': typeof ShellDocsProposalsIndexRoute
  '/versions/$version/': typeof ShellVersionsVersionIndexRoute
  '/v/$version/tasks/new': typeof ShellVVersionTasksNewRoute
  '/v/$version/w/$workstream': typeof ShellVVersionWWorkstreamRouteWithChildren
  '/versions/$version/area/$slug': typeof ShellVersionsVersionAreaSlugRoute
  '/versions/$version/deliverables/$deliverableId': typeof ShellVersionsVersionDeliverablesDeliverableIdRoute
  '/versions/$version/domain/$slug': typeof ShellVersionsVersionDomainSlugRoute
  '/versions/$version/feature/$slug': typeof ShellVersionsVersionFeatureSlugRoute
  '/versions/$version/milestones/$milestoneId': typeof ShellVersionsVersionMilestonesMilestoneIdRoute
  '/versions/$version/workstreams/$slug': typeof ShellVersionsVersionWorkstreamsSlugRoute
  '/docs/proposals/$id/': typeof ShellDocsProposalsIdIndexRoute
  '/docs/proposals/$id/changes/$changeId': typeof ShellDocsProposalsIdChangesChangeIdRoute
  '/docs/proposals/$id/changes/new': typeof ShellDocsProposalsIdChangesNewRoute
  '/v/$version/w/$workstream/tasks/new': typeof ShellVVersionWWorkstreamTasksNewRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/metrics': typeof MetricsRoute
  '/bugs': typeof ShellBugsRoute
  '/api/health': typeof ApiHealthRoute
  '/': typeof ShellIndexRoute
  '/v/$version': typeof ShellVVersionRouteWithChildren
  '/api/auth/github': typeof ApiAuthGithubRoute
  '/api/auth/hub-finish': typeof ApiAuthHubFinishRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/webhooks/github': typeof ApiWebhooksGithubRoute
  '/settings/auth/pair': typeof SettingsAuthPairRoute
  '/docs': typeof ShellDocsIndexRoute
  '/docs/catalog/$slug': typeof ShellDocsCatalogSlugRoute
  '/docs/proposals/new': typeof ShellDocsProposalsNewRoute
  '/workstreams/v/$version': typeof ShellWorkstreamsVVersionRoute
  '/docs/catalog': typeof ShellDocsCatalogIndexRoute
  '/docs/proposals': typeof ShellDocsProposalsIndexRoute
  '/versions/$version': typeof ShellVersionsVersionIndexRoute
  '/v/$version/tasks/new': typeof ShellVVersionTasksNewRoute
  '/v/$version/w/$workstream': typeof ShellVVersionWWorkstreamRouteWithChildren
  '/versions/$version/area/$slug': typeof ShellVersionsVersionAreaSlugRoute
  '/versions/$version/deliverables/$deliverableId': typeof ShellVersionsVersionDeliverablesDeliverableIdRoute
  '/versions/$version/domain/$slug': typeof ShellVersionsVersionDomainSlugRoute
  '/versions/$version/feature/$slug': typeof ShellVersionsVersionFeatureSlugRoute
  '/versions/$version/milestones/$milestoneId': typeof ShellVersionsVersionMilestonesMilestoneIdRoute
  '/versions/$version/workstreams/$slug': typeof ShellVersionsVersionWorkstreamsSlugRoute
  '/docs/proposals/$id': typeof ShellDocsProposalsIdIndexRoute
  '/docs/proposals/$id/changes/$changeId': typeof ShellDocsProposalsIdChangesChangeIdRoute
  '/docs/proposals/$id/changes/new': typeof ShellDocsProposalsIdChangesNewRoute
  '/v/$version/w/$workstream/tasks/new': typeof ShellVVersionWWorkstreamTasksNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/login': typeof LoginRoute
  '/metrics': typeof MetricsRoute
  '/_shell/bugs': typeof ShellBugsRoute
  '/api/health': typeof ApiHealthRoute
  '/_shell/': typeof ShellIndexRoute
  '/_shell/v/$version': typeof ShellVVersionRouteWithChildren
  '/_shell/versions/$version': typeof ShellVersionsVersionRouteWithChildren
  '/api/auth/github': typeof ApiAuthGithubRoute
  '/api/auth/hub-finish': typeof ApiAuthHubFinishRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/webhooks/github': typeof ApiWebhooksGithubRoute
  '/settings/auth/pair': typeof SettingsAuthPairRoute
  '/_shell/docs/': typeof ShellDocsIndexRoute
  '/_shell/docs/catalog/$slug': typeof ShellDocsCatalogSlugRoute
  '/_shell/docs/proposals/new': typeof ShellDocsProposalsNewRoute
  '/_shell/workstreams/v/$version': typeof ShellWorkstreamsVVersionRoute
  '/_shell/docs/catalog/': typeof ShellDocsCatalogIndexRoute
  '/_shell/docs/proposals/': typeof ShellDocsProposalsIndexRoute
  '/_shell/versions/$version/': typeof ShellVersionsVersionIndexRoute
  '/_shell/v/$version/tasks/new': typeof ShellVVersionTasksNewRoute
  '/_shell/v/$version/w/$workstream': typeof ShellVVersionWWorkstreamRouteWithChildren
  '/_shell/versions/$version/area/$slug': typeof ShellVersionsVersionAreaSlugRoute
  '/_shell/versions/$version/deliverables/$deliverableId': typeof ShellVersionsVersionDeliverablesDeliverableIdRoute
  '/_shell/versions/$version/domain/$slug': typeof ShellVersionsVersionDomainSlugRoute
  '/_shell/versions/$version/feature/$slug': typeof ShellVersionsVersionFeatureSlugRoute
  '/_shell/versions/$version/milestones/$milestoneId': typeof ShellVersionsVersionMilestonesMilestoneIdRoute
  '/_shell/versions/$version/workstreams/$slug': typeof ShellVersionsVersionWorkstreamsSlugRoute
  '/_shell/docs/proposals/$id/': typeof ShellDocsProposalsIdIndexRoute
  '/_shell/docs/proposals/$id/changes/$changeId': typeof ShellDocsProposalsIdChangesChangeIdRoute
  '/_shell/docs/proposals/$id/changes/new': typeof ShellDocsProposalsIdChangesNewRoute
  '/_shell/v/$version/w/$workstream/tasks/new': typeof ShellVVersionWWorkstreamTasksNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/metrics'
    | '/bugs'
    | '/api/health'
    | '/v/$version'
    | '/versions/$version'
    | '/api/auth/github'
    | '/api/auth/hub-finish'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/webhooks/github'
    | '/settings/auth/pair'
    | '/docs/'
    | '/docs/catalog/$slug'
    | '/docs/proposals/new'
    | '/workstreams/v/$version'
    | '/docs/catalog/'
    | '/docs/proposals/'
    | '/versions/$version/'
    | '/v/$version/tasks/new'
    | '/v/$version/w/$workstream'
    | '/versions/$version/area/$slug'
    | '/versions/$version/deliverables/$deliverableId'
    | '/versions/$version/domain/$slug'
    | '/versions/$version/feature/$slug'
    | '/versions/$version/milestones/$milestoneId'
    | '/versions/$version/workstreams/$slug'
    | '/docs/proposals/$id/'
    | '/docs/proposals/$id/changes/$changeId'
    | '/docs/proposals/$id/changes/new'
    | '/v/$version/w/$workstream/tasks/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/metrics'
    | '/bugs'
    | '/api/health'
    | '/'
    | '/v/$version'
    | '/api/auth/github'
    | '/api/auth/hub-finish'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/webhooks/github'
    | '/settings/auth/pair'
    | '/docs'
    | '/docs/catalog/$slug'
    | '/docs/proposals/new'
    | '/workstreams/v/$version'
    | '/docs/catalog'
    | '/docs/proposals'
    | '/versions/$version'
    | '/v/$version/tasks/new'
    | '/v/$version/w/$workstream'
    | '/versions/$version/area/$slug'
    | '/versions/$version/deliverables/$deliverableId'
    | '/versions/$version/domain/$slug'
    | '/versions/$version/feature/$slug'
    | '/versions/$version/milestones/$milestoneId'
    | '/versions/$version/workstreams/$slug'
    | '/docs/proposals/$id'
    | '/docs/proposals/$id/changes/$changeId'
    | '/docs/proposals/$id/changes/new'
    | '/v/$version/w/$workstream/tasks/new'
  id:
    | '__root__'
    | '/_shell'
    | '/login'
    | '/metrics'
    | '/_shell/bugs'
    | '/api/health'
    | '/_shell/'
    | '/_shell/v/$version'
    | '/_shell/versions/$version'
    | '/api/auth/github'
    | '/api/auth/hub-finish'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/webhooks/github'
    | '/settings/auth/pair'
    | '/_shell/docs/'
    | '/_shell/docs/catalog/$slug'
    | '/_shell/docs/proposals/new'
    | '/_shell/workstreams/v/$version'
    | '/_shell/docs/catalog/'
    | '/_shell/docs/proposals/'
    | '/_shell/versions/$version/'
    | '/_shell/v/$version/tasks/new'
    | '/_shell/v/$version/w/$workstream'
    | '/_shell/versions/$version/area/$slug'
    | '/_shell/versions/$version/deliverables/$deliverableId'
    | '/_shell/versions/$version/domain/$slug'
    | '/_shell/versions/$version/feature/$slug'
    | '/_shell/versions/$version/milestones/$milestoneId'
    | '/_shell/versions/$version/workstreams/$slug'
    | '/_shell/docs/proposals/$id/'
    | '/_shell/docs/proposals/$id/changes/$changeId'
    | '/_shell/docs/proposals/$id/changes/new'
    | '/_shell/v/$version/w/$workstream/tasks/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
  LoginRoute: typeof LoginRoute
  MetricsRoute: typeof MetricsRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiAuthGithubRoute: typeof ApiAuthGithubRoute
  ApiAuthHubFinishRoute: typeof ApiAuthHubFinishRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthMeRoute: typeof ApiAuthMeRoute
  ApiWebhooksGithubRoute: typeof ApiWebhooksGithubRoute
  SettingsAuthPairRoute: typeof SettingsAuthPairRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/metrics': {
      id: '/metrics'
      path: '/metrics'
      fullPath: '/metrics'
      preLoaderRoute: typeof MetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/bugs': {
      id: '/_shell/bugs'
      path: '/bugs'
      fullPath: '/bugs'
      preLoaderRoute: typeof ShellBugsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/docs/': {
      id: '/_shell/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof ShellDocsIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/settings/auth/pair': {
      id: '/settings/auth/pair'
      path: '/settings/auth/pair'
      fullPath: '/settings/auth/pair'
      preLoaderRoute: typeof SettingsAuthPairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/github': {
      id: '/api/webhooks/github'
      path: '/api/webhooks/github'
      fullPath: '/api/webhooks/github'
      preLoaderRoute: typeof ApiWebhooksGithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/hub-finish': {
      id: '/api/auth/hub-finish'
      path: '/api/auth/hub-finish'
      fullPath: '/api/auth/hub-finish'
      preLoaderRoute: typeof ApiAuthHubFinishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/github': {
      id: '/api/auth/github'
      path: '/api/auth/github'
      fullPath: '/api/auth/github'
      preLoaderRoute: typeof ApiAuthGithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/versions/$version': {
      id: '/_shell/versions/$version'
      path: '/versions/$version'
      fullPath: '/versions/$version'
      preLoaderRoute: typeof ShellVersionsVersionRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/v/$version': {
      id: '/_shell/v/$version'
      path: '/v/$version'
      fullPath: '/v/$version'
      preLoaderRoute: typeof ShellVVersionRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/versions/$version/': {
      id: '/_shell/versions/$version/'
      path: '/'
      fullPath: '/versions/$version/'
      preLoaderRoute: typeof ShellVersionsVersionIndexRouteImport
      parentRoute: typeof ShellVersionsVersionRoute
    }
    '/_shell/docs/proposals/': {
      id: '/_shell/docs/proposals/'
      path: '/docs/proposals'
      fullPath: '/docs/proposals/'
      preLoaderRoute: typeof ShellDocsProposalsIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/docs/catalog/': {
      id: '/_shell/docs/catalog/'
      path: '/docs/catalog'
      fullPath: '/docs/catalog/'
      preLoaderRoute: typeof ShellDocsCatalogIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/workstreams/v/$version': {
      id: '/_shell/workstreams/v/$version'
      path: '/workstreams/v/$version'
      fullPath: '/workstreams/v/$version'
      preLoaderRoute: typeof ShellWorkstreamsVVersionRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/docs/proposals/new': {
      id: '/_shell/docs/proposals/new'
      path: '/docs/proposals/new'
      fullPath: '/docs/proposals/new'
      preLoaderRoute: typeof ShellDocsProposalsNewRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/docs/catalog/$slug': {
      id: '/_shell/docs/catalog/$slug'
      path: '/docs/catalog/$slug'
      fullPath: '/docs/catalog/$slug'
      preLoaderRoute: typeof ShellDocsCatalogSlugRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/docs/proposals/$id/': {
      id: '/_shell/docs/proposals/$id/'
      path: '/docs/proposals/$id'
      fullPath: '/docs/proposals/$id/'
      preLoaderRoute: typeof ShellDocsProposalsIdIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/versions/$version/workstreams/$slug': {
      id: '/_shell/versions/$version/workstreams/$slug'
      path: '/workstreams/$slug'
      fullPath: '/versions/$version/workstreams/$slug'
      preLoaderRoute: typeof ShellVersionsVersionWorkstreamsSlugRouteImport
      parentRoute: typeof ShellVersionsVersionRoute
    }
    '/_shell/versions/$version/milestones/$milestoneId': {
      id: '/_shell/versions/$version/milestones/$milestoneId'
      path: '/milestones/$milestoneId'
      fullPath: '/versions/$version/milestones/$milestoneId'
      preLoaderRoute: typeof ShellVersionsVersionMilestonesMilestoneIdRouteImport
      parentRoute: typeof ShellVersionsVersionRoute
    }
    '/_shell/versions/$version/feature/$slug': {
      id: '/_shell/versions/$version/feature/$slug'
      path: '/feature/$slug'
      fullPath: '/versions/$version/feature/$slug'
      preLoaderRoute: typeof ShellVersionsVersionFeatureSlugRouteImport
      parentRoute: typeof ShellVersionsVersionRoute
    }
    '/_shell/versions/$version/domain/$slug': {
      id: '/_shell/versions/$version/domain/$slug'
      path: '/domain/$slug'
      fullPath: '/versions/$version/domain/$slug'
      preLoaderRoute: typeof ShellVersionsVersionDomainSlugRouteImport
      parentRoute: typeof ShellVersionsVersionRoute
    }
    '/_shell/versions/$version/deliverables/$deliverableId': {
      id: '/_shell/versions/$version/deliverables/$deliverableId'
      path: '/deliverables/$deliverableId'
      fullPath: '/versions/$version/deliverables/$deliverableId'
      preLoaderRoute: typeof ShellVersionsVersionDeliverablesDeliverableIdRouteImport
      parentRoute: typeof ShellVersionsVersionRoute
    }
    '/_shell/versions/$version/area/$slug': {
      id: '/_shell/versions/$version/area/$slug'
      path: '/area/$slug'
      fullPath: '/versions/$version/area/$slug'
      preLoaderRoute: typeof ShellVersionsVersionAreaSlugRouteImport
      parentRoute: typeof ShellVersionsVersionRoute
    }
    '/_shell/v/$version/w/$workstream': {
      id: '/_shell/v/$version/w/$workstream'
      path: '/w/$workstream'
      fullPath: '/v/$version/w/$workstream'
      preLoaderRoute: typeof ShellVVersionWWorkstreamRouteImport
      parentRoute: typeof ShellVVersionRoute
    }
    '/_shell/v/$version/tasks/new': {
      id: '/_shell/v/$version/tasks/new'
      path: '/tasks/new'
      fullPath: '/v/$version/tasks/new'
      preLoaderRoute: typeof ShellVVersionTasksNewRouteImport
      parentRoute: typeof ShellVVersionRoute
    }
    '/_shell/docs/proposals/$id/changes/new': {
      id: '/_shell/docs/proposals/$id/changes/new'
      path: '/docs/proposals/$id/changes/new'
      fullPath: '/docs/proposals/$id/changes/new'
      preLoaderRoute: typeof ShellDocsProposalsIdChangesNewRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/docs/proposals/$id/changes/$changeId': {
      id: '/_shell/docs/proposals/$id/changes/$changeId'
      path: '/docs/proposals/$id/changes/$changeId'
      fullPath: '/docs/proposals/$id/changes/$changeId'
      preLoaderRoute: typeof ShellDocsProposalsIdChangesChangeIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/v/$version/w/$workstream/tasks/new': {
      id: '/_shell/v/$version/w/$workstream/tasks/new'
      path: '/tasks/new'
      fullPath: '/v/$version/w/$workstream/tasks/new'
      preLoaderRoute: typeof ShellVVersionWWorkstreamTasksNewRouteImport
      parentRoute: typeof ShellVVersionWWorkstreamRoute
    }
  }
}

interface ShellVVersionWWorkstreamRouteChildren {
  ShellVVersionWWorkstreamTasksNewRoute: typeof ShellVVersionWWorkstreamTasksNewRoute
}

const ShellVVersionWWorkstreamRouteChildren: ShellVVersionWWorkstreamRouteChildren =
  {
    ShellVVersionWWorkstreamTasksNewRoute:
      ShellVVersionWWorkstreamTasksNewRoute,
  }

const ShellVVersionWWorkstreamRouteWithChildren =
  ShellVVersionWWorkstreamRoute._addFileChildren(
    ShellVVersionWWorkstreamRouteChildren,
  )

interface ShellVVersionRouteChildren {
  ShellVVersionTasksNewRoute: typeof ShellVVersionTasksNewRoute
  ShellVVersionWWorkstreamRoute: typeof ShellVVersionWWorkstreamRouteWithChildren
}

const ShellVVersionRouteChildren: ShellVVersionRouteChildren = {
  ShellVVersionTasksNewRoute: ShellVVersionTasksNewRoute,
  ShellVVersionWWorkstreamRoute: ShellVVersionWWorkstreamRouteWithChildren,
}

const ShellVVersionRouteWithChildren = ShellVVersionRoute._addFileChildren(
  ShellVVersionRouteChildren,
)

interface ShellVersionsVersionRouteChildren {
  ShellVersionsVersionIndexRoute: typeof ShellVersionsVersionIndexRoute
  ShellVersionsVersionAreaSlugRoute: typeof ShellVersionsVersionAreaSlugRoute
  ShellVersionsVersionDeliverablesDeliverableIdRoute: typeof ShellVersionsVersionDeliverablesDeliverableIdRoute
  ShellVersionsVersionDomainSlugRoute: typeof ShellVersionsVersionDomainSlugRoute
  ShellVersionsVersionFeatureSlugRoute: typeof ShellVersionsVersionFeatureSlugRoute
  ShellVersionsVersionMilestonesMilestoneIdRoute: typeof ShellVersionsVersionMilestonesMilestoneIdRoute
  ShellVersionsVersionWorkstreamsSlugRoute: typeof ShellVersionsVersionWorkstreamsSlugRoute
}

const ShellVersionsVersionRouteChildren: ShellVersionsVersionRouteChildren = {
  ShellVersionsVersionIndexRoute: ShellVersionsVersionIndexRoute,
  ShellVersionsVersionAreaSlugRoute: ShellVersionsVersionAreaSlugRoute,
  ShellVersionsVersionDeliverablesDeliverableIdRoute:
    ShellVersionsVersionDeliverablesDeliverableIdRoute,
  ShellVersionsVersionDomainSlugRoute: ShellVersionsVersionDomainSlugRoute,
  ShellVersionsVersionFeatureSlugRoute: ShellVersionsVersionFeatureSlugRoute,
  ShellVersionsVersionMilestonesMilestoneIdRoute:
    ShellVersionsVersionMilestonesMilestoneIdRoute,
  ShellVersionsVersionWorkstreamsSlugRoute:
    ShellVersionsVersionWorkstreamsSlugRoute,
}

const ShellVersionsVersionRouteWithChildren =
  ShellVersionsVersionRoute._addFileChildren(ShellVersionsVersionRouteChildren)

interface ShellRouteChildren {
  ShellBugsRoute: typeof ShellBugsRoute
  ShellIndexRoute: typeof ShellIndexRoute
  ShellVVersionRoute: typeof ShellVVersionRouteWithChildren
  ShellVersionsVersionRoute: typeof ShellVersionsVersionRouteWithChildren
  ShellDocsIndexRoute: typeof ShellDocsIndexRoute
  ShellDocsCatalogSlugRoute: typeof ShellDocsCatalogSlugRoute
  ShellDocsProposalsNewRoute: typeof ShellDocsProposalsNewRoute
  ShellWorkstreamsVVersionRoute: typeof ShellWorkstreamsVVersionRoute
  ShellDocsCatalogIndexRoute: typeof ShellDocsCatalogIndexRoute
  ShellDocsProposalsIndexRoute: typeof ShellDocsProposalsIndexRoute
  ShellDocsProposalsIdIndexRoute: typeof ShellDocsProposalsIdIndexRoute
  ShellDocsProposalsIdChangesChangeIdRoute: typeof ShellDocsProposalsIdChangesChangeIdRoute
  ShellDocsProposalsIdChangesNewRoute: typeof ShellDocsProposalsIdChangesNewRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellBugsRoute: ShellBugsRoute,
  ShellIndexRoute: ShellIndexRoute,
  ShellVVersionRoute: ShellVVersionRouteWithChildren,
  ShellVersionsVersionRoute: ShellVersionsVersionRouteWithChildren,
  ShellDocsIndexRoute: ShellDocsIndexRoute,
  ShellDocsCatalogSlugRoute: ShellDocsCatalogSlugRoute,
  ShellDocsProposalsNewRoute: ShellDocsProposalsNewRoute,
  ShellWorkstreamsVVersionRoute: ShellWorkstreamsVVersionRoute,
  ShellDocsCatalogIndexRoute: ShellDocsCatalogIndexRoute,
  ShellDocsProposalsIndexRoute: ShellDocsProposalsIndexRoute,
  ShellDocsProposalsIdIndexRoute: ShellDocsProposalsIdIndexRoute,
  ShellDocsProposalsIdChangesChangeIdRoute:
    ShellDocsProposalsIdChangesChangeIdRoute,
  ShellDocsProposalsIdChangesNewRoute: ShellDocsProposalsIdChangesNewRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
  LoginRoute: LoginRoute,
  MetricsRoute: MetricsRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiAuthGithubRoute: ApiAuthGithubRoute,
  ApiAuthHubFinishRoute: ApiAuthHubFinishRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthMeRoute: ApiAuthMeRoute,
  ApiWebhooksGithubRoute: ApiWebhooksGithubRoute,
  SettingsAuthPairRoute: SettingsAuthPairRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
